[package]
name = "venom-current-head-plugin-api-0-2-consumer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
venom-core = { workspace = true }
venom-scanner = { workspace = true, features = ["plugins"] }
