[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
authors = ["{{ authors }}"]
license = "MIT"

[dependencies]
async-trait = "0.1"
termivar-scanner = { git = "https://github.com/ITherso/termivar", branch = "main", default-features = false, features = ["plugins"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
