use async_trait::async_trait;
use venom_scanner::{Plugin, PluginCategory, PluginError, ScanFinding};

/// Starter implementation generated by the Venom plugin template.
pub struct GeneratedPlugin;

#[async_trait]
impl Plugin for GeneratedPlugin {
    fn id(&self) -> &str {
        "{{ plugin_id }}"
    }

    fn name(&self) -> &str {
        "{{ project-name }}"
    }

    fn version(&self) -> &str {
        env!("CARGO_PKG_VERSION")
    }

    fn description(&self) -> &str {
        "{{ plugin_description }}"
    }

    fn author(&self) -> &str {
        env!("CARGO_PKG_AUTHORS")
    }

    fn category(&self) -> PluginCategory {
        PluginCategory::Custom
    }

    fn enabled(&self) -> bool {
        true
    }

    async fn execute(&self, target: &str, payload: &str) -> Result<Vec<ScanFinding>, PluginError> {
        if !payload.contains("example-marker") {
            return Ok(Vec::new());
        }

        Ok(vec![ScanFinding {
            phase: 0,
            module_name: self.id().to_string(),
            severity: "INFO".to_string(),
            description: "Example marker observed".to_string(),
            evidence: target.to_string(),
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use venom_scanner::PluginRegistry;

    #[tokio::test]
    async fn registers_and_executes() {
        let registry = PluginRegistry::new();
        registry.register(Arc::new(GeneratedPlugin)).unwrap();

        let result = registry
            .execute("{{ plugin_id }}", "https://example.test", "example-marker")
            .await
            .unwrap();

        assert!(result.success);
        assert_eq!(result.findings.len(), 1);
    }
}
